version: '3.3'
services:
  agent-frontend:
    build: 
      context: .
      target: execute
      args:
        API_URL: "  backend_api: 'https://localhost:8090/'"
    restart: on-failure
    ports:
      - '3000:3000'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf

    # restart: on-failure
    # image: darkelfff/agent-front:latest
    # ports:
    #   - '3000:3000'
    # volumes:
    #   - ./docker/nginx.conf:/etc/nginx/nginx.conf
